### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by maketvgithub** [egeniq/android-tv-program-guide#21]
Hello again,

We are getting some crashes on Firebase, so I was wondering if someone else also got this error. Below is the log from Firebase:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:20 com.egeniq.androidtvprogramguide.row.ProgramGuideRowGridView{a496714 V.ED..... ......ID 0,0-1920,135 #7f0b01fa app:id/row}, adapter:com.egeniq.androidtvprogramguide.ProgramGuideListAdapter@bc62826, layout:com.egeniq.androidtvprogramguide.timeline.ProgramGuideTimelineGridView$1@6fedc67, context:rs.maketv.lakitv.leanback.activities.HomeActivity@fd690bd
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1116)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1838)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1940)
       at androidx.recyclerview.widget.RecyclerView.scrollBy(RecyclerView.java:1812)
       at com.egeniq.androidtvprogramguide.ProgramGuideFragment.onHorizontalScrolled(ProgramGuideFragment.kt:431)
       at com.egeniq.androidtvprogramguide.ProgramGuideFragment.access$onHorizontalScrolled(ProgramGuideFragment.kt:63)
       at com.egeniq.androidtvprogramguide.ProgramGuideFragment$setupComponents$onScrollListener$1.onScrolled(ProgramGuideFragment.kt:320)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dzolnai** [comment]
Interesting. What are the crash rates? 
Is it perhaps limited to a specific Android version or device (manufacturer)?

Were you able to reproduce it yourself?

**Comment by maketvgithub** [comment]
I was not able to reproduce it myself, but some of testers could.

It is limited to a specific Android version. It is 6.0.1 and device is some AOSP STB Device (G9SX)

**Comment by dzolnai** [comment]
> I was not able to reproduce it myself, but some of testers could.

Can you explain what the flow is when it crashes? Does it happen immediately when opening the guide? Or do you need to come back to it? Or does it happen when scrolling, etc.

**Comment by maketvgithub** [comment]
It happens when date is changed.

**Comment by maketvgithub** [comment]
Solved it. I'm closing this issue.

**Comment by dzolnai** [comment]
If the issue was in our codebase, please let us know how you fixed it, so we can include it 😃
