### ISSUE TITLE
Unable to parse DateTime 

### ISSUE THREAD

**Issue by MaheshaCN24** [egeniq/android-tv-program-guide#52]
Hi Sir,
you are passing nextTime and endTime in   2023-04-04T13:23:35Z this format.
in my case i am getting 2023-04-04T10:32:05+05:30 this format but i am not able to parse this format to your format can you please suggest how can i parse my data?

**Comment by dzolnai** [comment]
Hi, where does this exception get thrown exactly?

**Comment by MaheshaCN24** [comment]
2023-04-05 12:01:20.062 15588-15588/com.shemaroo.shemarootv E/com.shemaroo.shemarootv.EpgFragment: Unable to load example data!
    org.threeten.bp.format.DateTimeParseException: Text 'Wed Apr 05 11:32:05 GMT+05:30 2023' could not be parsed at index 0
        at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1588)
        at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
        at org.threeten.bp.ZonedDateTime.parse(ZonedDateTime.java:562)
        at com.shemaroo.shemarootv.EpgFragment.requestingProgramGuideFor$lambda-3(EpgFragment.kt:198)
        at com.shemaroo.shemarootv.EpgFragment.lambda$PUSzLCPAmk0YZ1pekSrc1onK0HQ(Unknown Source:0)
        at com.shemaroo.shemarootv.-$$Lambda$EpgFragment$PUSzLCPAmk0YZ1pekSrc1onK0HQ.call(Unknown Source:14)
        at rx.Single$4.call(Single.java:631)
        at rx.Single$4.call(Single.java:625)
        at rx.Single$1.call(Single.java:94)
        at rx.Single$1.call(Single.java:74)
        at rx.Single$2.call(Single.java:177)
        at rx.Single$2.call(Single.java:169)
        at rx.Single.subscribe(Single.java:1822)
        at rx.Single.subscribe(Single.java:1899)
        at rx.Single$19$1.call(Single.java:1954)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by MaheshaCN24** [comment]
val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss", Locale.ENGLISH)
  val sTime = ZonedDateTime.parse(nextTime, formatter)
this is the code i am using

**Comment by dzolnai** [comment]
Use the following formatter:

    DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ", Locale.ENGLISH)

**Comment by MaheshaCN24** [comment]
> Use the following formatter:
> 
> ```
> DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ", Locale.ENGLISH)
> ```

still getting the same exception

**Comment by MaheshaCN24** [comment]
instead of DateTime can use
"start_time_uts": 1680678125,
"stop_time_uts": 1680679925, these values?

**Comment by MaheshaCN24** [comment]
now I am getting it working fine 
Thank you for your support,
